-- P2.12 acceptance starts from an empty application schema. Synthetic users,
-- the single Company workspace, and bounded workflow data are created only by
-- scripts/p2-acceptance/fixture.ts after its local-only safety guard passes.
