import type { CmsPage } from '@/lib/data/pages';

export const DEVELOPMENT_CMS_EVIDENCE_PAGE: CmsPage = {
  id: 'development-evidence-page',
  slug: 'evidence-editorial-page',
  title: 'Editorial CMS evidence page',
  contentJson: {},
  contentHtml:
    '<p>This reviewed local fixture verifies the generic public CMS presentation without changing remote content.</p><h2>Published content</h2><p>Only public presentation fields are rendered.</p><h2>Safe destinations</h2><p>Links and media remain constrained by the public policy.</p><h2>Script isolation</h2><p>Advanced CMS script slots are intentionally ignored.</p>',
  heroSettings: {
    backgroundColor: '#211d1b',
    overlayColor: '#000000',
    overlayOpacity: 0,
    headingAlignment: 'left',
    textAlignment: 'left',
    buttonAlignment: 'left',
    heading: 'Editorial CMS evidence page',
    text: 'A development-only fixture for public presentation acceptance.',
    buttonLabel: 'Browse the Knowledge Base',
    buttonHref: '/knowledge-base',
  },
  backgroundImageMediaId: null,
  status: 'published',
  publishedAt: '2026-09-05T00:00:00.000Z',
  scheduledFor: null,
  metaTitle: 'Editorial CMS evidence page | Mandoob',
  metaDescription: 'Development-only evidence for the generic public CMS presentation.',
  canonicalUrl: '/evidence-editorial-page',
  noindex: true,
  schemaMarkup: { '@context': 'https://schema.org', '@type': 'WebPage' },
  createdBy: null,
  updatedBy: null,
  scriptHead: 'development evidence slot: must not render',
  scriptBodyStart: 'development evidence slot: must not render',
  scriptBodyEnd: 'development evidence slot: must not render',
  deletedAt: null,
  createdAt: '2026-09-05T00:00:00.000Z',
  updatedAt: '2026-09-05T00:00:00.000Z',
};
