import type { PDFFont, PDFPage, RGB } from 'pdf-lib';

export type ReceiptPdfInput = {
  tenantName: string;
  tenantColor: string | null;
  clientName: string;
  customerName: string | null;
  invoiceId: string;
  label: string;
  amount: string;
  status: string;
  paidAt: string | null;
  paymentMethod: string | null;
  paymentProvider: string | null;
  refunds: { amount: string; reason: string | null; status: string }[];
};

export function isReceiptEligible(status: string): boolean {
  return status === 'paid' || status === 'refunded' || status === 'partially_refunded';
}

export function receiptFilename(invoiceId: string): string {
  const safe = invoiceId.replace(/[^a-zA-Z0-9-]+/g, '-').replace(/-+/g, '-').replace(/^-|-$/g, '');
  return `receipt-${safe || 'invoice'}.pdf`;
}

export async function generateReceiptPdf(input: ReceiptPdfInput): Promise<Uint8Array> {
  const { PDFDocument, StandardFonts, rgb } = await import('pdf-lib');
  const doc = await PDFDocument.create();
  const page = doc.addPage([595.28, 841.89]);
  const regular = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);
  const accent = parseHex(input.tenantColor, rgb) ?? rgb(0.05, 0.46, 0.43);
  const ink = rgb(0.08, 0.09, 0.11);
  const muted = rgb(0.36, 0.39, 0.45);

  page.drawRectangle({ x: 0, y: 780, width: 595.28, height: 62, color: accent });
  page.drawText(input.tenantName, { x: 42, y: 806, size: 18, font: bold, color: rgb(1, 1, 1) });
  page.drawText('Payment receipt', { x: 42, y: 742, size: 28, font: bold, color: rgb(0.08, 0.09, 0.11) });
  page.drawText(`Invoice ${input.invoiceId}`, {
    x: 42,
    y: 714,
    size: 11,
    font: regular,
    color: rgb(0.36, 0.39, 0.45),
  });

  drawField(page, bold, regular, 'Client', input.clientName, 42, 650, muted, ink);
  drawField(page, bold, regular, 'Customer', input.customerName ?? 'Not linked', 42, 598, muted, ink);
  drawField(page, bold, regular, 'Description', input.label, 42, 546, muted, ink);
  drawField(page, bold, regular, 'Amount', input.amount, 42, 494, muted, ink);
  drawField(page, bold, regular, 'Status', input.status, 42, 442, muted, ink);
  drawField(
    page,
    bold,
    regular,
    'Paid at',
    input.paidAt ? new Date(input.paidAt).toLocaleString('en-GB') : 'Not paid',
    42,
    390,
    muted,
    ink,
  );
  drawField(page, bold, regular, 'Payment provider', input.paymentProvider ?? 'Not recorded', 42, 338, muted, ink);
  drawField(page, bold, regular, 'Payment method', input.paymentMethod ?? 'Not recorded', 42, 286, muted, ink);

  let y = 224;
  if (input.refunds.length > 0) {
    page.drawText('Refunds', { x: 42, y, size: 12, font: bold, color: rgb(0.08, 0.09, 0.11) });
    y -= 24;
    for (const refund of input.refunds.slice(0, 6)) {
      page.drawText(`${refund.amount} · ${refund.status}${refund.reason ? ` · ${refund.reason}` : ''}`, {
        x: 42,
        y,
        size: 10,
        font: regular,
        color: rgb(0.36, 0.39, 0.45),
        maxWidth: 500,
      });
      y -= 18;
    }
  }

  page.drawLine({ start: { x: 42, y: 150 }, end: { x: 553, y: 150 }, thickness: 1, color: rgb(0.86, 0.88, 0.91) });
  page.drawText('Generated by Mandoob', { x: 42, y: 116, size: 10, font: regular, color: rgb(0.45, 0.48, 0.54) });

  return doc.save();
}

function drawField(
  page: PDFPage,
  bold: PDFFont,
  regular: PDFFont,
  label: string,
  value: string,
  x: number,
  y: number,
  muted: RGB,
  ink: RGB,
) {
  page.drawText(label, { x, y, size: 10, font: bold, color: muted });
  page.drawText(value, { x, y: y - 22, size: 14, font: regular, color: ink, maxWidth: 500 });
}

function parseHex(value: string | null, makeRgb: (red: number, green: number, blue: number) => RGB): RGB | null {
  const match = value?.match(/^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i);
  if (!match) return null;
  return makeRgb(
    Number.parseInt(match[1], 16) / 255,
    Number.parseInt(match[2], 16) / 255,
    Number.parseInt(match[3], 16) / 255,
  );
}
