import type { EstimatorCatalog, EstimatorFee } from './public-contracts';

const commonFees = (
  authorityId: string,
  registrationMinor: number,
  licenseMinor: number,
  officeType: 'flexi' | 'physical' | 'none',
): EstimatorFee[] => [
  {
    id: `${authorityId}-registration`,
    authorityId,
    activityId: null,
    feeType: 'registration',
    label: 'Registration planning allowance',
    category: 'government',
    sourceContext: 'Illustrative localhost demo assumption; confirm with the selected authority.',
    recurrence: 'one_time',
    amountMinor: registrationMinor,
    quantityBasis: 'flat',
    optionId: null,
    timelineDays: { min: 2, max: 4 },
    documentKeys: ['passport-copy'],
  },
  {
    id: `${authorityId}-license`,
    authorityId,
    activityId: null,
    feeType: 'license',
    label: 'Licence planning allowance',
    category: 'authority',
    sourceContext:
      'Illustrative localhost demo assumption; activity approval and current fees vary.',
    recurrence: 'annual',
    amountMinor: licenseMinor,
    quantityBasis: 'flat',
    optionId: null,
    timelineDays: { min: 4, max: 8 },
    documentKeys: ['passport-copy', 'activity-summary'],
  },
  ...(officeType === 'none'
    ? []
    : [
        {
          id: `${authorityId}-office-${officeType}`,
          authorityId,
          activityId: null,
          feeType: `office_${officeType}`,
          label:
            officeType === 'flexi'
              ? 'Flexi workspace planning allowance'
              : 'Office planning allowance',
          category: 'office' as const,
          sourceContext:
            'Illustrative localhost demo allowance; lease and sufficiency require confirmation.',
          recurrence: 'annual' as const,
          amountMinor: officeType === 'flexi' ? 600000 : 1200000,
          quantityBasis: 'office' as const,
          optionId: officeType,
          timelineDays: { min: 1, max: 3 },
          documentKeys: ['workspace-evidence'],
        },
      ]),
  {
    id: `${authorityId}-shareholder`,
    authorityId,
    activityId: null,
    feeType: 'shareholder',
    label: 'Additional shareholder document review',
    category: 'professional_service',
    sourceContext: 'Illustrative localhost demo assumption per shareholder after the first.',
    recurrence: 'one_time',
    amountMinor: 50000,
    quantityBasis: 'additional_shareholder',
    optionId: null,
    timelineDays: { min: 0, max: 1 },
    documentKeys: ['shareholder-documents'],
  },
  {
    id: `${authorityId}-visa`,
    authorityId,
    activityId: null,
    feeType: 'visa',
    label: 'Visa, medical and identity planning allowance',
    category: 'visa_and_identity',
    sourceContext:
      'Illustrative localhost demo assumption; quota, eligibility and external charges vary.',
    recurrence: 'one_time',
    amountMinor: 375000,
    quantityBasis: 'visa',
    optionId: null,
    timelineDays: { min: 6, max: 10 },
    documentKeys: ['passport-copy', 'passport-photo'],
  },
  {
    id: `${authorityId}-bank`,
    authorityId,
    activityId: null,
    feeType: 'addon_bank_account',
    label: 'Bank-account application assistance',
    category: 'banking',
    sourceContext: 'Assistance only; it does not guarantee account opening or bank acceptance.',
    recurrence: 'one_time',
    amountMinor: 200000,
    quantityBasis: 'add_on',
    optionId: 'bank-account-assistance',
    timelineDays: { min: 0, max: 0 },
    documentKeys: ['activity-summary'],
  },
  {
    id: `${authorityId}-tax`,
    authorityId,
    activityId: null,
    feeType: 'addon_tax',
    label: 'Tax-registration assistance',
    category: 'tax',
    sourceContext: 'Assistance only; tax obligations and outcomes require separate confirmation.',
    recurrence: 'one_time',
    amountMinor: 150000,
    quantityBasis: 'add_on',
    optionId: 'tax-registration-assistance',
    timelineDays: { min: 0, max: 0 },
    documentKeys: ['licence-copy'],
  },
  {
    id: `${authorityId}-attestation`,
    authorityId,
    activityId: null,
    feeType: 'addon_attestation',
    label: 'Attestation coordination allowance',
    category: 'attestation',
    sourceContext:
      'Illustrative coordination allowance; third-party charges depend on the documents.',
    recurrence: 'one_time',
    amountMinor: 180000,
    quantityBasis: 'add_on',
    optionId: 'document-attestation',
    timelineDays: { min: 2, max: 5 },
    documentKeys: ['documents-for-attestation'],
  },
];

export const DEMO_ESTIMATOR_CATALOG: EstimatorCatalog = {
  id: 'mandoob-local-estimator-demo',
  version: 'p1.08-demo-2026-09-05',
  currency: 'AED',
  sourceState: 'indicative-demo',
  sourceLabel: 'Local illustrative demo catalog',
  sourceContext:
    'These values demonstrate estimator behavior on localhost. They are not current authority prices or a quote.',
  jurisdictions: [
    {
      id: 'mainland',
      label: 'Mainland',
      description:
        'An emirate authority context for activities intended to operate in the UAE market.',
    },
    {
      id: 'free_zone',
      label: 'Free Zone',
      description: 'An authority-specific setup context with package and activity requirements.',
    },
    {
      id: 'offshore',
      label: 'Offshore',
      description: 'A non-resident structure context requiring suitability and eligibility review.',
    },
  ],
  authorities: [
    {
      id: 'dubai-mainland',
      label: 'Dubai mainland authority context',
      description:
        'Illustrative Dubai mainland path; exact authority and activity approval require confirmation.',
      jurisdiction: 'mainland',
      emirate: 'dubai',
      activityIds: ['professional-services', 'commercial-trading'],
      legalStructureIds: ['llc', 'branch'],
      officeTypeIds: ['physical'],
      addOnIds: ['bank-account-assistance', 'tax-registration-assistance', 'document-attestation'],
      shareholderRange: { min: 1, max: 10 },
      visaRange: { min: 0, max: 6 },
    },
    {
      id: 'dmcc',
      label: 'DMCC',
      description: 'Illustrative Free Zone context for demonstrating compatible estimator choices.',
      jurisdiction: 'free_zone',
      emirate: 'dubai',
      activityIds: ['professional-services', 'commercial-trading'],
      legalStructureIds: ['fz_llc', 'branch'],
      officeTypeIds: ['flexi'],
      addOnIds: ['bank-account-assistance', 'tax-registration-assistance', 'document-attestation'],
      shareholderRange: { min: 1, max: 6 },
      visaRange: { min: 0, max: 6 },
    },
    {
      id: 'rak-icc',
      label: 'RAK ICC',
      description:
        'Illustrative offshore context; residence visas are not supported in this demo path.',
      jurisdiction: 'offshore',
      emirate: 'ras_al_khaimah',
      activityIds: ['holding-activities'],
      legalStructureIds: ['offshore_company'],
      officeTypeIds: ['none'],
      addOnIds: ['bank-account-assistance', 'document-attestation'],
      shareholderRange: { min: 1, max: 10 },
      visaRange: { min: 0, max: 0 },
    },
  ],
  activities: [
    {
      id: 'professional-services',
      label: 'Professional services',
      description:
        'A broad demo activity family; exact licensed activity naming requires confirmation.',
      code: 'DEMO-PRO',
      category: 'Professional',
      jurisdictions: ['mainland', 'free_zone'],
    },
    {
      id: 'commercial-trading',
      label: 'Commercial trading',
      description: 'A demo trading family; products and external approvals require confirmation.',
      code: 'DEMO-TRD',
      category: 'Commercial',
      jurisdictions: ['mainland', 'free_zone'],
    },
    {
      id: 'holding-activities',
      label: 'Holding activities',
      description: 'A demo offshore planning category, not legal or tax suitability advice.',
      code: 'DEMO-HLD',
      category: 'Holding',
      jurisdictions: ['offshore'],
    },
  ],
  legalStructures: [
    {
      id: 'llc',
      label: 'Limited liability company',
      description: 'Structure availability and liability effects require legal confirmation.',
    },
    {
      id: 'fz_llc',
      label: 'Free Zone company',
      description: 'Authority naming and formation requirements vary.',
    },
    {
      id: 'branch',
      label: 'Branch',
      description: 'Parent-company and approval requirements vary by authority.',
    },
    {
      id: 'offshore_company',
      label: 'Offshore company',
      description: 'Suitability, ownership and tax treatment require professional advice.',
    },
  ],
  officeTypes: [
    {
      id: 'none',
      label: 'No office in this demo path',
      description: 'Only shown where the selected source supports it.',
    },
    {
      id: 'flexi',
      label: 'Flexi or shared workspace',
      description: 'Package sufficiency depends on authority, activity and visa needs.',
    },
    {
      id: 'physical',
      label: 'Physical office',
      description: 'Lease, size and registration requirements require confirmation.',
    },
  ],
  addOns: [
    {
      id: 'bank-account-assistance',
      label: 'Bank-account application assistance',
      description: 'Preparation support only; account opening is not guaranteed.',
    },
    {
      id: 'tax-registration-assistance',
      label: 'Tax-registration assistance',
      description: 'Administrative support only; no tax outcome or obligation is asserted.',
    },
    {
      id: 'document-attestation',
      label: 'Document attestation coordination',
      description: 'Requirements and third-party charges depend on the documents.',
    },
  ],
  fees: [
    ...commonFees('dubai-mainland', 620000, 1500000, 'physical'),
    ...commonFees('dmcc', 850000, 1250000, 'flexi'),
    ...commonFees('rak-icc', 700000, 850000, 'none'),
  ],
  documents: [
    {
      id: 'passport-copy',
      label: 'Passport copy',
      description: 'For each relevant shareholder or applicant.',
    },
    {
      id: 'passport-photo',
      label: 'Passport-style photo',
      description: 'Format requirements vary.',
    },
    {
      id: 'activity-summary',
      label: 'Business activity summary',
      description: 'Exact authority wording requires confirmation.',
    },
    {
      id: 'shareholder-documents',
      label: 'Additional shareholder documents',
      description: 'Corporate shareholders may require further records.',
    },
    {
      id: 'workspace-evidence',
      label: 'Workspace or lease evidence',
      description: 'Only where required by the selected path.',
    },
    {
      id: 'licence-copy',
      label: 'Licence copy when available',
      description: 'May be needed for later assistance steps.',
    },
    {
      id: 'documents-for-attestation',
      label: 'Documents requiring attestation',
      description: 'The issuing country and document type affect requirements.',
    },
  ],
  assumptions: [
    'The selected activity and legal structure remain subject to authority review.',
    'Visa quota and workspace sufficiency require separate confirmation.',
    'Timelines are illustrative working-day ranges and are not approval promises.',
  ],
  inclusions: [
    'Itemized illustrative allowances from the selected local demo catalog.',
    'Visible assumptions, required-document guidance and recurrence labels.',
  ],
  exclusions: [
    'Unlisted government, authority, immigration, medical and Emirates ID charges.',
    'Bank, tax, legal, translation, attestation and other third-party outcomes or charges not shown as line items.',
    'Payment-provider fees, professional advice and changes after authority review.',
  ],
};
